kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-persistent-gp2
  namespace: odf-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
